{
  "@type": "NewsArticle",
  "identifier": "2022--03--19--en--myrss--rss--NewsArticle--c5fa5994ce92da85fc217ca8e02c63cb",
  "url": "https://www.davidhaney.io/tpl-and-error-handling-continuations/",
  "headline": "TPL and Error Handling & Continuation Tasks",
  "publisher": {
    "@type": "Organization",
    "name": "www.davidhaney.io",
    "url": "https://www.davidhaney.io/index.xml"
  },
  "description": "Two of my colleagues (one from work and one from a user group) kindly pointed out to me that in my last post I omitted Continuation Tasksas a means of Error Handling for the TPL. As such, I will expand upon my last post with an example of handling errors via a Continuation Task.\nContinuing where we left off last, the following code will utilize a Task Continuation to handle errors within Tasks.",
  "keywords": [],
  "author": {
    "@type": "Person",
    "name": "unknown",
    "url": "https://www.davidhaney.io/index.xml"
  },
  "discussionUrl": "https://www.davidhaney.io/tpl-and-error-handling-continuations/",
  "sameAs": "https://www.davidhaney.io/tpl-and-error-handling-continuations/",
  "dateCreated": "2022-03-19T09:29:28.236Z",
  "datePublished": "2012-08-12T23:21:30.000Z",
  "dateModified": "2022-03-19T09:29:28.236Z",
  "interactionStatistic": [],
  "headline_zh-Hans": "TPL和错误处理及延续任务",
  "headline_zh-Hant": "TPL和錯誤處理及延續任務",
  "@context": [
    "https://schema.org",
    {
      "@vocab": "http://schema.org/",
      "@language": "en",
      "headline_zh-Hans": {
        "@id": "headline",
        "@language": "zh-Hans"
      },
      "headline_zh-Hant": {
        "@id": "headline",
        "@language": "zh-Hant"
      },
      "@version": 1.1,
      "description_zh-Hans": {
        "@id": "description",
        "@language": "zh-Hans"
      },
      "description_zh-Hant": {
        "@id": "description",
        "@language": "zh-Hant"
      }
    }
  ],
  "description_zh-Hans": "我的两位同事（一位来自工作单位，一位来自用户组）友好地指出，在我的上一篇文章中，我忽略了延续任务作为TPL的错误处理手段。因此，我将在上一篇文章的基础上，通过一个延续任务处理错误的例子来展开。\n继续我们上次的话题，下面的代码将利用一个任务延续来处理任务中的错误。",
  "description_zh-Hant": "我的兩位同事（一位來自工作單位，一位來自用戶組）友好地指出，在我的上一篇文章中，我忽略了延續任務作為TPL的錯誤處理手段。因此，我將在上一篇文章的基礎上，通過一個延續任務處理錯誤的例子來展開。\n繼續我們上次的話題，下面的代碼將利用一個任務延續來處理任務中的錯誤。"
}