{
  "@type": "NewsArticle",
  "identifier": "2022--03--28--en--myfeed--HackerNews--NewsArticle--30825863",
  "url": "https://news.ycombinator.com/item?id=30825863",
  "headline": "Among Us Servers Have Been Down for over 48 Hours Due to DDoS Attack",
  "publisher": {
    "@type": "Organization",
    "name": "HackerNews",
    "url": "https://news.ycombinator.com",
    "logo": "https://hn.buzzing.cc/avatar.png"
  },
  "description": "",
  "keywords": [],
  "author": {
    "@type": "Person",
    "name": "bryan0",
    "url": "https://news.ycombinator.com/user?id=bryan0"
  },
  "discussionUrl": "https://news.ycombinator.com/item?id=30825863",
  "sameAs": "https://kotaku.com/among-us-down-servers-ddos-update-innersloth-attack-sab-1848709508",
  "dateCreated": "2022-03-28T02:22:25.786Z",
  "datePublished": "2022-03-28T01:01:21.000Z",
  "dateModified": "2022-03-28T02:22:25.786Z",
  "interactionStatistic": [
    {
      "@type": "InteractionCounter",
      "interactionType": {
        "@type": "LikeAction"
      },
      "userInteractionCount": 3
    },
    {
      "@type": "InteractionCounter",
      "interactionType": {
        "@type": "CommentAction"
      },
      "userInteractionCount": 0
    }
  ],
  "headline_zh-Hans": "由于DDoS攻击，\"我们 \"的服务器已瘫痪超过48小时",
  "headline_zh-Hant": "由於DDoS攻擊，\"我們 \"的服務器已癱瘓超過48小時",
  "@context": [
    "https://schema.org",
    {
      "@vocab": "http://schema.org/",
      "@language": "en",
      "headline_zh-Hans": {
        "@id": "headline",
        "@language": "zh-Hans"
      },
      "headline_zh-Hant": {
        "@id": "headline",
        "@language": "zh-Hant"
      },
      "@version": 1.1
    }
  ]
}