{
  "@type": "NewsArticle",
  "identifier": "2022--04--22--en--myfeed--HackerNews--NewsArticle--31120813",
  "url": "https://news.ycombinator.com/item?id=31120813",
  "headline": "Python 3.11 Preview: Task and Exception Groups",
  "publisher": {
    "@type": "Organization",
    "name": "HackerNews",
    "url": "https://news.ycombinator.com",
    "logo": "https://hn.buzzing.cc/avatar.png"
  },
  "description": "",
  "keywords": [],
  "author": {
    "@type": "Person",
    "name": "EntICOnc",
    "url": "https://news.ycombinator.com/user?id=EntICOnc"
  },
  "discussionUrl": "https://news.ycombinator.com/item?id=31120813",
  "sameAs": "https://realpython.com/python311-exception-groups/",
  "dateCreated": "2022-04-22T13:35:01.104Z",
  "datePublished": "2022-04-22T12:30:02.000Z",
  "dateModified": "2022-04-22T13:35:01.104Z",
  "interactionStatistic": [
    {
      "@type": "InteractionCounter",
      "interactionType": {
        "@type": "LikeAction"
      },
      "userInteractionCount": 2
    },
    {
      "@type": "InteractionCounter",
      "interactionType": {
        "@type": "CommentAction"
      },
      "userInteractionCount": 0
    }
  ],
  "headline_zh-Hans": "Python 3.11预览。任务和异常组",
  "headline_zh-Hant": "Python 3.11預覽。任務和異常組",
  "@context": [
    "https://schema.org",
    {
      "@vocab": "http://schema.org/",
      "@language": "en",
      "headline_zh-Hans": {
        "@id": "headline",
        "@language": "zh-Hans"
      },
      "headline_zh-Hant": {
        "@id": "headline",
        "@language": "zh-Hant"
      },
      "@version": 1.1
    }
  ]
}