{
  "@type": "NewsArticle",
  "identifier": "2022--04--29--en--myfeed--HackerNews--NewsArticle--31200614",
  "url": "https://news.ycombinator.com/item?id=31200614",
  "headline": "Network faults in Hetzner's Falkenstein data center",
  "publisher": {
    "@type": "Organization",
    "name": "HackerNews",
    "url": "https://news.ycombinator.com",
    "logo": "https://hn.buzzing.cc/avatar.png"
  },
  "description": "",
  "keywords": [],
  "author": {
    "@type": "Person",
    "name": "surewe",
    "url": "https://news.ycombinator.com/user?id=surewe"
  },
  "discussionUrl": "https://news.ycombinator.com/item?id=31200614",
  "sameAs": "https://status.hetzner.com/incident/129728ce-ba25-49b6-96cc-aafcd39ab0b7",
  "dateCreated": "2022-04-29T02:53:29.961Z",
  "datePublished": "2022-04-29T02:15:46.000Z",
  "dateModified": "2022-04-29T02:53:29.961Z",
  "interactionStatistic": [
    {
      "@type": "InteractionCounter",
      "interactionType": {
        "@type": "LikeAction"
      },
      "userInteractionCount": 2
    },
    {
      "@type": "InteractionCounter",
      "interactionType": {
        "@type": "CommentAction"
      },
      "userInteractionCount": 0
    }
  ]
}